Setup Prettier #157
rwjblue/ember-cli-content-security-policy pull request #162
Opened 2020-11-18 20:55 UTC by zg3d

Fixes issue #157 

-added .pretterrc.json
-added prettier script in package.json
-the script was ran on the repo
- added formatting command in contributing document

Please let me know if i need to make changes

2020-11-19 14:27 UTC, jelhan requested changes
Thanks a lot for picking this one up! :clap:

Would it okay for you to align it more with Prettier RFC? I think this would be more future proof and cause less noise when Prettier is added to default blueprints.

2020-11-19 14:27 UTC, jelhan commented on package.json
> +    "format": "prettier --write \"./**/*.{md,json,js,yml}\""
I would prefer to setup Prettier as ESLint plugin as described in the RFC: https://emberjs.github.io/rfcs/0628-prettier.html#detailed-design My main motivation is that we don't need to change much when this RFC is implemented in Ember CLI.

2020-11-19 14:27 UTC, jelhan commented on .prettierrc.json
> +}
Any reasons for this specific configuration? I would prefer to use the configuration as defined by Prettier RFC: https://emberjs.github.io/rfcs/0628-prettier.html#prettier Mostly to use the same as other Ember addons.

2020-11-19 16:16 UTC, zg3d commented
I'll implement all the changes

2020-11-23 15:27 UTC, jelhan approved these changes
Thanks a lot!

2020-11-23 15:27 UTC, merged